version: '3'
services:
  neo4j-db:
      image: neo4j:5.12.0
      environment:
        NEO4J_AUTH: neo4j/password
        NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      ports:
        - "7474:7474"
        - "7687:7687"
      volumes:
        - data:/data
        - logs:/logs

  flask-app:
    build:
      context: .
    command: ./wait-for-it.sh -t 30 neo4j-db:7687 -- python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - neo4j-db

volumes:
  data:
  logs:
